version: "3"
services: 
  gps: 
    image: 
    ports:
      - 8881:8881
  
  rewards:
    image: 
    ports:
      - 8882:8882
  
  tripdeals:
    image: 
    ports:
      - 8883:8883
      
  tourguide:
    depends_on:
      - gps
      - tripdeals
    image: 
    ports:
      - 8080:8080